### ISSUE TITLE
SiteURL - without tenant

### ISSUE THREAD

**Issue by cool-abhi** [estruyf/node-sppkg-deploy#1]
Thanks for creating this repo. The site URL in the code is accepting tenant name only. Not all tenant are configured with ".sharepoint.com' . Can you change this to accept complete site URL instead tenant name  ? Should able to work with one site parameter and remove tenant parameter

siteUrl = `https://${this._internalOptions.tenant}.sharepoint.com/${this._internalOptions.site}`;

**Comment by estruyf** [comment]
Will create an additional hostname property.

**Comment by estruyf** [comment]
I have done an update to the package. This one now supports to specify the hostname. I currently released it as a beta. If you want to test it, just try to install: `npm install node-sppkg-deploy@beta-v1.1.0`.

Documentation is updated in the dev branch: https://github.com/estruyf/node-sppkg-deploy/tree/dev#hostname-optional

**Comment by dhavalshah01** [comment]
yes the update on the package works. Just a suggestion, wouldn't it be better to club together the teanant/hostname with the site parameter as single parameter ..something like "AppCatalogUrl". As it will be just more confusing for the developers on how to configure it.

**Comment by estruyf** [comment]
New version is released with an `absoluteUrl` property.

**Comment by estruyf** [comment]
BTW: `npm install node-sppkg-deploy@1.1.1`

**Comment by cool-abhi** [comment]
Thanks Elio it worked

**Comment by estruyf** [comment]
Thanks again for the suggestion!
