### ISSUE TITLE
sppkg doesnt complete deployment

### ISSUE THREAD

**Issue by ErikCohenDev** [estruyf/node-sppkg-deploy#3]
Version: "node-sppkg-deploy": "^1.1.1"

Looks like the package doesn't finish deployment.

I get these two errors:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Username argument is required
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'Id' of undefined

The Username is defined in the config.

**Comment by estruyf** [comment]
Can you post your configuration please, like:

```
sppkgDeploy.deploy({
    username: "username", // The user that will deploy the file
    password: "password", // The password of the user
    tenant: "tenant", // The tenant name. Example: contoso
    site: "sites/catalog", // Path to your app catalog site
    filename: "app.sppkg", // Filename of the package
    skipFeatureDeployment: true, // Do you want to skip the feature deployment (SharePoint Framework)
    verbose: true // Do you want to show logging during the deployment
});
```

You can, of course, leave out the sensitive information.

**Comment by ErikCohenDev** [comment]
Sorry for the delay @estruyf, here is the config info you requested. 

sppkgDeploy.deploy({
        username: "spuser",
        password: "sppass",
        tenant: "cohenpts",
        site: "sites/appcatalog",
        filename:  "app.sppkg",
        skipFeatureDeployment: false,
        verbose: true
      });

**Comment by estruyf** [comment]
I see you have **verbose** logging turned on. That should normally give you more information about all the calls that happened. Can you also share this output, because that is useful information when and where it failed.

I also created a new version (v1.1.2). This contains a couple of extra checks and will by default log the error message. Before this was only when verbose was set to `true`.

**Comment by ErikCohenDev** [comment]
thanks for the help @estruyf ill try out the new version and create a new issue if it occurs again.

**Comment by estruyf** [comment]
You can just respond on this issue.
