### ISSUE TITLE
sppkg is not deployed on SP2016 on prem

### ISSUE THREAD

**Issue by rgilou** [estruyf/node-sppkg-deploy#5]
hello, 
thanks for this tool that will complete the automation process for SPFX ;)

I've created a gulp task and tried to deploy a SPFX webpart package on SP2016 (on prem) but it  doesn't replace the sppgk file already existing in the app catalog,
do you have an idea why ? here are the parameters I've used in the gulp task:

sppkgDeploy.deploy({
        username: environmentInfo.username,
        password: environmentInfo.password,
        absoluteUrl: http://myapp/sites/appcatalog,
        filename: sp2016lab.sppkg,
        skipFeatureDeployment: false,
        sp2016:true,
        verbose: true 
});

thanks,
Gilles

**Comment by estruyf** [comment]
@rgilou this module only deploys the solution package in the app catalog. It does not upload the solution package. For uploading the file to your app catalog, you can make use of the `gulp-spsync-creds` module: https://github.com/estruyf/gulp-spsync-creds / https://www.npmjs.com/package/gulp-spsync-creds

**Comment by rgilou** [comment]
ok thanks, I understand now the whole process ;)
