### ISSUE TITLE
AppVersion not updating

### ISSUE THREAD

**Issue by randompixel** [estruyf/node-sppkg-deploy#7]
Hi,

I'm not sure if it's a problem with this package or not, but when I use it to upload the sppkg file, the AppVersion doesn't get updated in Sharepoint.

![image](https://user-images.githubusercontent.com/2316601/42270902-e19e3738-7f79-11e8-9267-a013108ee324.png)

I have updated both the package.json and package-solution.json, then run `gulp bundle --ship && gulp package-solution --ship`. This has updated the manifest.xml with the correct version number. When I upload via this tool
```
gulp sppkg-deploy --username "username" --password "password" --tenant "tenant" --catalogsite "sites/apps" --verbose
```
it _appears_ to update - the `updated by` changes to "a few seconds ago" and the version appeared to update. But because the App Version doesn't increment it makes it unclear whether the new version has uploaded or not.

Uploading the same sppkg file manually does indeed overwrite the original one and update the AppVersion field. Therefore it appears to be either this package or the API not doing something correctly.

I also noticed this package only works if you've uploaded it manually first. If you try to use it for an initial upload it seems to fail with a 404 saying the file isn't there (which is true, it's the initial upload! :D)

Thanks in advance.

**Comment by randompixel** [comment]
Looking at the version history in Sharepoint:

![image](https://user-images.githubusercontent.com/2316601/42271334-f3116d5e-7f7a-11e8-9d6e-cce96c8fdb57.png)
Numbers 1.0 and 4.0 are the manual uploads. Numbers 2.0 and 3.0 are via the sppkg-deploy function. The package number was changed for version 3.0 as you can see from the script outputs here.
![image](https://user-images.githubusercontent.com/2316601/42271492-62aba0b2-7f7b-11e8-9d8c-dae20951b2a5.png)

**Comment by estruyf** [comment]
@randompixel this could indeed be a bug as it uses the processQuery API. If you are using SharePoint Online, I would encourage you to test out the `node-sp-alm` package. This one uses the latest ALM API which should automatically process these changes. https://github.com/estruyf/node-sp-alm

This dependency was created before the ALM APIs were in place, and also supports on-premises.

**Comment by randompixel** [comment]
Hi @estruyf ,

I switched to using the package you suggested and it is working much better!

Thank you! 👍
